### ISSUE TITLE
Any way to average over many runs?

### ISSUE THREAD

**Issue by ryanpeach** [iai-callgrind/iai-callgrind#299]
I have a vector of inputs (thousands), and I'd like to benchmark the average stats of calling each one on the function. I only see so far on how to benchmark the total set.

**Comment by gamma0987** [comment]
Sorry, I need more context. Can you please provide a minimal example with the current and expected outcome?

**Comment by ryanpeach** [comment]
I'm not sure but I think I want something like:

```rust
#[benches::multiple(0, 1, .., 1000)]
```

Maybe like this

```rust
#[benches::multiple_from_vec(0..1000)]
```

Or maybe there's a better thing to do than 1000 separate benchmarks. Again, like an average.

Replacing

```
bench_foo() {
  for i in 0..1000 {
    foo(i)
  }
}
```

With

```
#[benches::average_over(0..1000)]
bench_foo(i) {
  foo(i)
}
```

**Comment by gamma0987** [comment]
Thanks for the examples. At first glance, it should be feasible to calculate and display the average instead of the individual benchmarks. The main problem would be the range/iterator, but, I'll have a look into it. For the time being, there's the possibility to create benchmarks from the contents of a file:

```rust
#[benches::multiple_from_file(file = "inputs_0_to_1000")]
```
