### ISSUE TITLE
Machine readable output

### ISSUE THREAD

**Issue by infogulch** [iai-callgrind/iai-callgrind#31]
In the context of running in CI, it would be nice to have the tool output data in a machine readable format like json or csv.

**Comment by gamma0987** [comment]
Thanks for your interest in iai-callgrind.

> In the context of running in CI, it would be nice to have the tool output data in a machine readable format like json or csv.

Sounds great! Choosing different output formats could be for example integrated via an environment variable like `IAI_CALLGRIND_OUTPUT_FORMAT=default|json|pretty-json|csv|...`

**Comment by infogulch** [comment]
You could also pass a flag, I think something like like `cargo bench --bench iai_benches -- --format=json` would pass the arg to the harness.

**Comment by gamma0987** [comment]
Maybe a command line argument would be ok here, too. But, I'm not a big fan of command line arguments for cargo benches because they can cause problems if you want to run all benchmarks of your crate just with `cargo bench -- --output-format=json`. In contrast, environment variables reach the benchmarking harness without causing trouble.

**Comment by infogulch** [comment]
Well it already does that now with iai_callgrind

```shell
 ⮞ cargo bench --bench run_iai -- --output-format=json
    Finished bench [optimized] target(s) in 0.16s
     Running benches/run_iai.rs (target/release/deps/run_iai-06a167e4e37dea10)
valgrind: Unknown option: --output-format=json
```

idk

**Comment by gamma0987** [comment]
An env var is the best solution in my opinion.

Regarding your example: Currently, all command line arguments are passed through to valgrind as callgrind arguments, so the error from valgrind for `--output-format` is supposed to happen.

If we would add an iai-callgrind argument like `--output-format`, we would have to make sure that this argument is sorted out and removed from the list of arguments passed to valgrind. Also, to make sure that these additional arguments are not interfering with valgrind arguments in the future, it would be necessary to differentiate clearly between valgrind arguments and iai-callgrind arguments. I thought about different solutions:

* Add a prefix to iai-callgrind arguments `--iai-callgrind-output-format=...`. If that argument is too long we could allow an alias like `--iaic-output-format`.
* Use a single dash for iai-callgrind arguments -> `-output-format=...`.
* Instead of prefixing iai-callgrind arguments, prefix valgrind (callgrind) arguments with `--callgrind-toggle-collect` (and dhat arguments with --dhat-...)
* Use a single argument `--callgrind-args='--toggle-collect=...'` for callgrind arguments, so all command line arguments are interpreted as iai-callgrind arguments and no prefix for `--output-format` would be necessary. The additional advantage of this solution would be, that passing arguments to other tools like dhat etc. could be done with `--dhat-args=...`

Maybe there are more solutions. Although it introduces a major change in handling command line arguments, I tend to the last solution. It would keep the command line argument names nice and short and it's future proof.

**Comment by infogulch** [comment]
That all seems reasonable to me. I think an env var is fine in lieu of revamping arg handling.

**Comment by infogulch** [comment]
FYI I'm integrating iai-callgrind in [scryer-prolog](https://github.com/mthom/scryer-prolog):

* [My PR](https://github.com/mthom/scryer-prolog/pull/2153)
  * I'm invoking the iai benchmark in github actions [here](https://github.com/mthom/scryer-prolog/pull/2153/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR161)
  * Actions logs [here](https://github.com/mthom/scryer-prolog/actions/runs/6832003450/job/18582198347?pr=2153)
  * The code is a bit funny, but you can see the condensed benchmark definitions [here](https://github.com/mthom/scryer-prolog/pull/2153/files#diff-58923892c04e52ec23e63927864003b4584709678d225fdd7eba3421087ecf60R116)
    * They are used just below in `fn bench_criterion`, and `run_iai.rs`
  * Also note that it uploads iai and criterion benchmark results as artifacts [here](https://github.com/mthom/scryer-prolog/actions/runs/6832003450?pr=2153)

Considering this last point, I wonder if it would be better to parse the callgrind out file directly than have iai-callgrind change its output. I'm not sure what I think about that; do you have an opinion?

**Comment by gamma0987** [comment]
Thanks for sharing. Great to see iai-callgrind in use :)

I thought about an additional possibility regarding the json report. I would like to dump a json summary in addition to the default output and add an argument --save-summary=json. So, in the ci you can see the usual summary and additionally you can use the json data for own reports.

>  I wonder if it would be better to parse the callgrind out file directly than have iai-callgrind change its output. I'm not sure what I think about that; do you have an opinion?

Depends on what additional infos you would like to extract from the callgrind out files. If possible, I would try to avoid parsing the raw callgrind output file. This can end up to be a lot of work. Maybe it can be integrated into the iai-callgrind json report?

**Comment by infogulch** [comment]
> in the ci you can see the usual summary and additionally you can use the json data for own reports.

I like that. Would that be output in the target/iai directory?

> I would try to avoid parsing the raw callgrind output file

Yeah you're probably right. I'm not sure what else I'd want to get out of it, the out file just looks tantalizingly full of details.

**Comment by gamma0987** [comment]
> Would that be output in the target/iai directory?

Yes, I think so. I would save the summary of each benchmark run in a `summary.json` or something like that next to the usual output files of each benchmark run.

**Comment by gamma0987** [comment]
I'm pretty close to finish this feature. What I haven't done yet is the `--output-format=json` option and csv output, but `--save-summary=json|pretty-json` and the env var `IAI_CALLGRIND_SAVE_SUMMARY=json|pretty-json` which let iai-callgrind create the `summary.json` files are stable. Do you really need the `csv` output and the `output-format` option? Could you please give me feedback on whether all the information you need for your own reports is stored in the summary files. You can have a look at the [json schema](https://github.com/iai-callgrind/iai-callgrind/blob/602295873e3c02eb5dcc72fc5ebd2c5660bde173/iai-callgrind-runner/schemas/summary.v1.schema.json) or download and inspect the artifacts of the last ci run https://github.com/iai-callgrind/iai-callgrind/suites/18316579565/artifacts/1059680027 from the development branch which contain a lot of real world examples for summary.json files.

**Comment by infogulch** [comment]
I don't have any need for csv in particular, just the output in some consistently machine readable for, which json sufficiently provides. If I need to transform it somehow, well `jq` is there for me. :)

Looking at the schema and sample artifact, it looks like it has everything I would need. 

Thank you!

**Comment by gamma0987** [comment]
> Looking at the schema and sample artifact, it looks like it has everything I would need. I'll experiment with it and report back this week.

Great! I'm keeping this issue open then until you report back. But, I'll merge the current state of the development branch into main. The current implementation is stable so far and you can checkout the more stable main branch if you want.
