### ISSUE TITLE
Setup for library_benchmark_group

### ISSUE THREAD

**Issue by infogulch** [iai-callgrind/iai-callgrind#32]
It would be nice if `library_benchmark_group!{}` also supported a unitary `setup` function.

**Comment by gamma0987** [comment]
Like in `binary_benchmark_group!{}`? So, something like this?

```rust
fn some_setup_func() {}

#[library_benchmark]
fn my_bench() {}

library_benchmark_group!{ name = my_group; setup = some_setup_func; benchmarks = my_bench };
```

**Comment by infogulch** [comment]
Yes, though I did find the bench annotation workaround it would be nice to have a global setup func.

In my case I'm loading files, preparing the runtime, etc in the setup func via a shared global OnceCell, which I'm also reusing in criterion benchmarks. The idea is to rely on iai benchmarks in CI but still allow criterion benchmarks when running locally.

**Comment by gamma0987** [comment]
> Yes, though I did find the bench annotation workaround it would be nice to have a global setup func.

I think, I see what your trying to achieve. But, you can't share global variables between different benchmarks. The reason is, that each benchmark runs in an individual process. So, a global `OnceCell` doesn't make much sense. Instead, return the content of the `OnceCell` directly from the setup function roughly like:

```rust
#[inline(never)]
fn setup() -> MyResult {
   // ...
}

#[library_benchmark]
#[bench::my_id(setup())]`
fn my_bench(my_result: MyResult) {
   // ...
}
```

I'm not sure if it would help much, but, what do you think about using `before`, `after` just like in `binary_benchmark_group`? In the `before` function, which would run once before all benchmarks in the `libary_benchmark_group`, you could do all the heavy stuff, then serialize a result and dump it to disk. In the `setup_func` function at `#[bench]` level you could deserialize the file and finally make use of it in the benchmark. Something like this:

```rust
#[derive(Serialize, Deserialize)]
struct MySetup {
    // ...
}

#[inline(never)]
fn before_func() {
    // do all the heavy stuff serialize and dump to disk
}

#[inline(never)]
fn setup_func() -> MySetup {
    // read and deserialize dumped file
}

#[library_benchmark]
#[bench::my_id(setup_func())]
fn my_bench(my_setup: MySetup) {
    // benchmark
}

library_benchmark_group!{ name = my_group; before = before_func; benchmarks = my_bench };
```

**Comment by infogulch** [comment]
> The reason is, that each benchmark runs in an individual process. So, a global OnceCell doesn't make much sense. Instead, return the content of the OnceCell directly from the setup function roughly like:

Good call. I didn't know that the iai benchmark runs execute in a different process.
